In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from xgboost import XGBClassifier

In [3]:
train_df = pd.read_csv("atlantis_citizens_final.csv")
test_df  = pd.read_csv("test_atlantis_hidden.csv")

In [4]:
train_df = train_df.dropna(subset=["Wealth_Index", "House_Size_sq_ft", "Life_Expectancy"])

In [5]:
train_df

,Citizen_ID,Diet_Type,District_Name,Occupation,Wealth_Index,House_Size_sq_ft,Life_Expectancy,Vehicle_Owned,Work_District,Bio_Hash
0,CIT_15935,Exotic Imports,Coral Slums,Scribe,1491.0,100.0,42.0,Fin Bicycle,Mariana Plaza,b81cb8ce
1,CIT_11623,Seafood,Coral Slums,Fisher,1596.0,100.0,49.0,Sea Scooter,Deep Trench,72f48eef
2,CIT_8026,Seafood,Mariana Plaza,Warrior,3921.0,533.0,37.0,Sea Scooter,Deep Trench,0abde296
4,CIT_0275,Seaweed,Deep Trench,Warrior,25985.0,2673.0,54.0,Sea Scooter,Deep Trench,c77829e2
5,CIT_7475,Seaweed,Mariana Plaza,Warrior,6173.0,911.0,47.0,Sea Scooter,Deep Trench,e4023d89
...,...,...,...,...,...,...,...,...,...,...
15746,CIT_10602,Seaweed,Mariana Plaza,Merchant,2896.0,428.0,59.0,Sea Scooter,Mariana Plaza,268659a4
15747,CIT_0865,Seaweed,Coral Slums,Miner,1671.0,100.0,47.0,No Vehicle,Mariana Plaza,ca287a73
15748,CIT_0809,Exotic Imports,Mariana Plaza,Scribe,4656.0,756.0,53.0,Fin Bicycle,Mariana Plaza,717ca395
15749,CIT_10750,Seafood,The Golden Reef,Merchant,17529.0,3961.0,72.0,No Vehicle,The Golden Reef,34fb8c73
15750,CIT_6381,Seaweed,Coral Slums,Warrior,1439.0,100.0,32.0,Sea Scooter,Coral Slums,ac857e92

In [6]:
X_train = train_df[["Diet_Type","District_Name","Wealth_Index","House_Size_sq_ft","Life_Expectancy","Vehicle_Owned","Work_District"]]
X_train

,Diet_Type,District_Name,Wealth_Index,House_Size_sq_ft,Life_Expectancy,Vehicle_Owned,Work_District
0,Exotic Imports,Coral Slums,1491.0,100.0,42.0,Fin Bicycle,Mariana Plaza
1,Seafood,Coral Slums,1596.0,100.0,49.0,Sea Scooter,Deep Trench
2,Seafood,Mariana Plaza,3921.0,533.0,37.0,Sea Scooter,Deep Trench
4,Seaweed,Deep Trench,25985.0,2673.0,54.0,Sea Scooter,Deep Trench
5,Seaweed,Mariana Plaza,6173.0,911.0,47.0,Sea Scooter,Deep Trench
...,...,...,...,...,...,...,...
15746,Seaweed,Mariana Plaza,2896.0,428.0,59.0,Sea Scooter,Mariana Plaza
15747,Seaweed,Coral Slums,1671.0,100.0,47.0,No Vehicle,Mariana Plaza
15748,Exotic Imports,Mariana Plaza,4656.0,756.0,53.0,Fin Bicycle,Mariana Plaza
15749,Seafood,The Golden Reef,17529.0,3961.0,72.0,No Vehicle,The Golden Reef
15750,Seaweed,Coral Slums,1439.0,100.0,32.0,Sea Scooter,Coral Slums

In [7]:
y_train = train_df["Occupation"].map({"Warrior":0, "Merchant":1, "Fisher":2, "Miner":3, "Scribe":4})
X_test = test_df[["Diet_Type","District_Name","Wealth_Index","House_Size_sq_ft","Life_Expectancy","Vehicle_Owned","Work_District"]]
X_test

,Diet_Type,District_Name,Wealth_Index,House_Size_sq_ft,Life_Expectancy,Vehicle_Owned,Work_District
0,Seaweed,Mariana Plaza,2851,453,53,Sea Scooter,Coral Slums
1,Seaweed,Mariana Plaza,5176,815,58,No Vehicle,Deep Trench
2,Exotic Imports,Deep Trench,3772,390,29,Fin Bicycle,The Golden Reef
3,Seaweed,Deep Trench,1288,131,44,No Vehicle,Deep Trench
4,Seafood,Deep Trench,1736,182,43,Sea Scooter,The Golden Reef
...,...,...,...,...,...,...,...
3933,Exotic Imports,Mariana Plaza,3537,572,50,Fin Bicycle,Mariana Plaza
3934,Seafood,Coral Slums,1769,116,41,Sea Scooter,Deep Trench
3935,Seaweed,The Golden Reef,7972,1689,72,No Vehicle,Coral Slums
3936,Exotic Imports,Coral Slums,1904,138,34,Sea Scooter,Coral Slums
3937,Seaweed,The Golden Reef,9441,1974,67,Submarine,The Golden Reef

In [8]:
num_imputer = SimpleImputer(strategy="median")
scaler = MinMaxScaler()

In [9]:
list_one = ["Wealth_Index", "House_Size_sq_ft", "Life_Expectancy"]
# this line of code is not important since i have already dropped all the columns containing the na values

X_train.loc[:, list_one] = num_imputer.fit_transform(X_train[list_one])
X_test.loc[:, list_one] = num_imputer.transform(X_test[list_one])

X_train.loc[:, list_one] = scaler.fit_transform(X_train[list_one])
X_test.loc[:, list_one] = scaler.transform(X_test[list_one])

C:\Users\Hetal Koul\AppData\Local\Temp\ipykernel_1788\3443140330.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.00314594 0.00709749 0.00471127 ... 0.01184955 0.00153643 0.01434624]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X_test.loc[:, list_one] = scaler.transform(X_test[list_one])
C:\Users\Hetal Koul\AppData\Local\Temp\ipykernel_1788\3443140330.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.03565657 0.07222222 0.02929293 ... 0.16050505 0.00383838 0.18929293]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X_test.loc[:, list_one] = scaler.transform(X_test[list_one])
C:\Users\Hetal Koul\AppData\Local\Temp\ipykernel_1788\3443140330.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.36666667 0.42222222 0.1        ... 0.57777778 0.15555556 0.52222222]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X_test.loc[:, list_one] = scaler.transform(X_test[list_one])

In [10]:
l_two = ["Diet_Type", "District_Name", "Vehicle_Owned", "Work_District"]

In [11]:

im = SimpleImputer(strategy="most_frequent")
X_train.loc[:, l_two] = im.fit_transform(X_train[l_two])
X_test.loc[:, l_two] = im.transform(X_test[l_two])

ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
ohe.fit(X_train[l_two])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [12]:
tr_ohe = pd.DataFrame(ohe.transform(X_train[l_two]), columns=ohe.get_feature_names_out(l_two), index=X_train.index)
te_ohe = pd.DataFrame(ohe.transform(X_test[l_two]), columns=ohe.get_feature_names_out(l_two), index=X_test.index)

In [13]:
X_train_final = pd.concat([X_train[list_one], tr_ohe], axis=1)
X_test_final = pd.concat([X_test[list_one], te_ohe], axis=1)

In [15]:
model = XGBClassifier(n_estimators=300,learning_rate=0.1,max_depth=3,subsample=0.8,colsample_bytree=0.8,objective="multi:softmax",eval_metric="mlogloss",num_class=5,random_state=42,n_jobs=-1)

In [16]:
model.fit(X_train_final, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1, num_class=5, ...)

In [17]:
test_solution = model.predict(X_test_final)

In [18]:
submission = pd.DataFrame({ "Citizen_ID": test_df["Citizen_ID"], "Occupation": test_solution})

In [19]:
submission.to_csv("sub_1.csv", index=False)